name: example
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Package locale: niente pin di versione (stesso repo).
  rive_native:
    path: ../

  cupertino_icons:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
